# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcnetCli < Formula
  desc "CLI for Knowledge Graph"
  homepage "https://github.com/fogfish/arcnet-cli"
  version "0.1.30"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fogfish/arcnet-cli/releases/download/0.1.30/arc_0.1.30_darwin_amd64"
      sha256 "2b5020d3fbc38c2c91d92f48792fa76fcd72d966b235c6607770dc681d3eb498"

      define_method(:install) do
        bin.install "arc_0.1.30_darwin_amd64" => "arc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fogfish/arcnet-cli/releases/download/0.1.30/arc_0.1.30_darwin_arm64"
      sha256 "9e2bb668fb73bc223614822508fe0a36ed0e36bf1725b446f4ce29388904e03c"

      define_method(:install) do
        bin.install "arc_0.1.30_darwin_arm64" => "arc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fogfish/arcnet-cli/releases/download/0.1.30/arc_0.1.30_linux_amd64"
      sha256 "bffdd3243e4043e4b0a93eb8c2ed6eec84ecdacef7d08cdf71c80fba94ba95fc"
      define_method(:install) do
        bin.install "arc_0.1.30_linux_amd64" => "arc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fogfish/arcnet-cli/releases/download/0.1.30/arc_0.1.30_linux_arm64"
      sha256 "8ce824b149c7adad6e93d90bb19c7578c6ff9d2f7952073c1b44a2d420f36190"
      define_method(:install) do
        bin.install "arc_0.1.30_linux_arm64" => "arc"
      end
    end
  end

  test do
    system "#{bin}/arc --version"
  end
end
